---
- name: Install google authenticator
  apt:
    name: libpam-google-authenticator
    state: present

- name: Enable two-factor authentication
  lineinfile:
    path: /etc/pam.d/common-auth
    regexp: 'auth            required        pam_google_authenticator.so        nullok'
    insertbefore: '^auth*[success=1 default=ignore]*pam_unix.so*nullok_secure*'
    line: ' auth            required        pam_google_authenticator.so         nullok'

